### ISSUE TITLE
[Feature Request] Add Deepslate variant of Quartz Ore

### ISSUE THREAD

**Issue by Kitteh6660** [Unixkitty/overworld_quartz#1]
Since Deepslate is now a thing, would it be possible to add Deepslate Quartz Ore for consistency? If even possible, allow the ore to generate all the way down to -64 via config, even tweak so it can generate into Deepslate layer.

Would not be too hard.

**Comment by Unixkitty** [comment]
@Kitteh6660 Why not, will see about it this week.

**Comment by Vazkii** [comment]
Bout a year later on this one but yes, doubling down on this request

**Comment by Unixkitty** [comment]
Heh, I honestly thought there was barely anybody using this small mod besides myself on my server, but okay, I'll add this as a configurable in a couple of days when I get back home.

**Comment by Unixkitty** [comment]
Added in version 1.1.2.0, should also be configurable via vanilla datapack stuff. https://github.com/Unixkitty/overworld_quartz/blob/1.19.2/src/main/resources/data/overworld_quartz/worldgen/placed_feature/ore_overworld_quartz.json
